
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 29;
  public static final int CIERREPARENTESIS = 12;
  public static final int MULTIPLICACION = 30;
  public static final int PUNTOYCOMA = 3;
  public static final int DOSPUNTOS = 14;
  public static final int APERTURAPARENTESIS = 11;
  public static final int INFO = 27;
  public static final int BARRA = 6;
  public static final int EJECUTAR = 26;
  public static final int ETIQUETA = 22;
  public static final int APERTURALLAVE = 8;
  public static final int PORCENTAJE = 21;
  public static final int TIPO = 19;
  public static final int VALORES = 23;
  public static final int COMA = 15;
  public static final int APERTURACORCHETE = 9;
  public static final int TOTAL = 24;
  public static final int EOF = 0;
  public static final int DEF = 5;
  public static final int PIE = 7;
  public static final int EXTRA = 25;
  public static final int CANTIDAD = 20;
  public static final int CIERRELLAVE = 2;
  public static final int error = 1;
  public static final int EJEY = 18;
  public static final int DIVICION = 31;
  public static final int EJEX = 17;
  public static final int COMENTARIO = 32;
  public static final int UNIR = 16;
  public static final int NUMEROENTERO = 4;
  public static final int TITULO = 13;
  public static final int MAS = 28;
  public static final int CIERRECORCHETE = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CIERRELLAVE",
  "PUNTOYCOMA",
  "NUMEROENTERO",
  "DEF",
  "BARRA",
  "PIE",
  "APERTURALLAVE",
  "APERTURACORCHETE",
  "CIERRECORCHETE",
  "APERTURAPARENTESIS",
  "CIERREPARENTESIS",
  "TITULO",
  "DOSPUNTOS",
  "COMA",
  "UNIR",
  "EJEX",
  "EJEY",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "ETIQUETA",
  "VALORES",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "INFO",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVICION",
  "COMENTARIO"
  };
}

